[pytest]
testpaths = tests
markers =
    REQ_F01: Tests para REQ-F01 (Registro de pacientes)
    REQ_F02: Tests para REQ-F02 (Agendar turno)
    REQ_F03: Tests para REQ-F03 (Confirmación de turno)
    REQ_N02: Tests para REQ-N02 (Recordatorios automáticos)
    REQ_F04: Tests para REQ-F04 (Cancelar turno)
    REQ_F05: Tests para REQ-F05 (Turnos disponibles)
    REQ_NF02: Tests para REQ-NF02 (Datos cifrados)
    turnosweb: Todos los tests del sistema TurnosWeb
pythonpath = .
